# Generated by Django 5.2.7 on 2025-10-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=100)),
                ('b_des', models.TextField()),
                ('b_image', models.ImageField(upload_to='books')),
            ],
        ),
    ]
